# Generated by Django 4.2.7 on 2023-12-03 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 20, 20, 27, 979876), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='total_view',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
