# Generated by Django 4.2.7 on 2023-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date_create_alter_blog_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='total_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
